spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  profiles:
    active: dev, fast
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  application:
    name: final4j
server:
  port: 8080